image: python:3.8

stages:
  - build
  - deploy

variables:
  VENV_DIR: "base"

before_script:
  - python -m venv $VENV_DIR
  - source $VENV_DIR/bin/activate


build:
  stage: build
  script:
    - echo "Building the project..."

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
  only:
    - main  # Runs the deploy job only on the main branch
