image: python:3.8

stages:
  - build
  - deploy

variables:
  VENV_DIR: "base"

before_script:
  # Install PowerShell on the Python image
  - apt-get update
  - apt-get install -y wget apt-transport-https software-properties-common
  - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -cs)/prod.list" -O /etc/apt/sources.list.d/mssql-release.list
  - apt-get update
  - apt-get install -y powershell
  - pwsh -Command "& { ./$VENV_DIR/Scripts/Activate.ps1 }"


build:
  stage: build
  script:
    - echo "Building the project..."
    # Add build commands here

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
  only:
    - main  # Change to your branch name if different
