image: mcr.microsoft.com/windows/servercore:ltsc2022  # Use a Windows image

stages:
  - build
  - deploy

variables:
  VENV_DIR: "base"

before_script:
  - powershell -ExecutionPolicy Bypass -Command "& { python -m venv $env:VENV_DIR }"
  - powershell -ExecutionPolicy Bypass -Command "& { .\$env:VENV_DIR\Scripts\Activate.ps1 }"


build:
  stage: build
  script:
    - powershell -ExecutionPolicy Bypass -Command "& { echo 'Building the project...' }"
    # Add build commands here


deploy:
  stage: deploy
  script:
    - powershell -ExecutionPolicy Bypass -Command "& { echo 'Deploying the project...' }"
    # Add your deployment commands here
  only:
    - main  # Replace with 'master' if your branch is named 'master'
