image: python:3.8

stages:
  - build
  - deploy

variables:
  VENV_DIR: "base"

before_script:
  - source $VENV_DIR/Scripts/activate
  - pip install pytest # For bash

build:
  stage: build
  script:
    - echo "Building the project..."

 # Adjust this to your testing command

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
  only:
    - master
