image: mcr.microsoft.com/powershell

stages:
  - build
  - deploy

variables:
  VENV_DIR: "base"

before_script:
  # Activate virtual environment using PowerShell
  - powershell -ExecutionPolicy Bypass -File $VENV_DIR\Scripts\Activate.ps1

build:
  stage: build
  script:
    - echo "Building the project..."
    # Add build commands here

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here, e.g.,
    # - powershell -File deploy_script.ps1
  only:
    - main  # Change to your branch name if different
