image: python:3.8

stages:
  - build
  - test
  - deploy

variables:
  VENV_DIR: "base"

before_script:
  - python -m venv $VENV_DIR
  - source $VENV_DIR/Scripts/Activate.ps1
  # Install pytest if not using requirements.txt

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - pytest  # Run tests with pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
  only:
    - master
